<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $presentation->title }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            font-family: DejaVu Sans, sans-serif;
            background: #fff;
            color: #1a1a2e;
        }

        .cover {
            page-break-after: always;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            padding: 60px;
            background: #f8f7ff;
            border-left: 8px solid #6366f1;
        }

        .cover-label {
            font-size: 11px;
            font-weight: 700;
            color: #6366f1;
            text-transform: uppercase;
            letter-spacing: 0.15em;
            margin-bottom: 20px;
        }

        .cover h1 {
            font-size: 42px;
            font-weight: 800;
            color: #1a1a2e;
            line-height: 1.2;
            margin-bottom: 16px;
        }

        .cover-topic {
            font-size: 18px;
            color: #6b7280;
            margin-bottom: 40px;
        }

        .cover-meta {
            font-size: 12px;
            color: #9ca3af;
        }

        .slide {
            page-break-after: always;
            padding: 50px 60px;
            min-height: 100vh;
            position: relative;
        }

        .slide-header {
            display: flex;
            align-items: center;
            gap: 14px;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #e0e7ff;
        }

        .slide-num {
            width: 32px;
            height: 32px;
            border-radius: 50%;
            background: #6366f1;
            color: white;
            font-size: 13px;
            font-weight: 700;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .slide h2 {
            font-size: 26px;
            font-weight: 700;
            color: #1a1a2e;
        }

        .bullets {
            list-style: none;
            margin-bottom: 30px;
        }

        .bullets li {
            display: flex;
            align-items: flex-start;
            gap: 12px;
            font-size: 15px;
            color: #374151;
            line-height: 1.6;
            margin-bottom: 12px;
        }

        .bullet-dot {
            width: 8px;
            height: 8px;
            border-radius: 50%;
            background: #6366f1;
            margin-top: 7px;
            flex-shrink: 0;
        }

        .notes-box {
            background: #fffbeb;
            border-left: 4px solid #f59e0b;
            border-radius: 4px;
            padding: 14px 18px;
            margin-top: 20px;
        }

        .notes-label {
            font-size: 10px;
            font-weight: 700;
            color: #d97706;
            text-transform: uppercase;
            letter-spacing: 0.1em;
            margin-bottom: 6px;
        }

        .notes-text {
            font-size: 13px;
            color: #92400e;
            line-height: 1.6;
        }

        .footer {
            position: absolute;
            bottom: 24px;
            left: 60px;
            right: 60px;
            display: flex;
            justify-content: space-between;
            font-size: 10px;
            color: #d1d5db;
            border-top: 1px solid #f3f4f6;
            padding-top: 10px;
        }
    </style>
</head>
<body>

{{-- Cover page --}}
<div class="cover">
    <div class="cover-label">AI Generated Presentation</div>
    <h1>{{ $presentation->title }}</h1>
    <p class="cover-topic">{{ $presentation->topic }}</p>
    <p class="cover-meta">{{ count($presentation->structure['slides']) }} slides · Generated by MindDraft AI</p>
</div>

{{-- Slides --}}
@foreach($presentation->structure['slides'] as $index => $slide)
    <div class="slide">
        <div class="slide-header">
            <div class="slide-num">{{ $index + 1 }}</div>
            <h2>{{ $slide['title'] }}</h2>
        </div>

        <ul class="bullets">
            @foreach($slide['bullets'] as $bullet)
                <li>
                    <div class="bullet-dot"></div>
                    <span>{{ $bullet }}</span>
                </li>
            @endforeach
        </ul>

        @if(!empty($slide['notes']))
            <div class="notes-box">
                <div class="notes-label">Speaker Notes</div>
                <div class="notes-text">{{ $slide['notes'] }}</div>
            </div>
        @endif

        <div class="footer">
            <span>{{ $presentation->title }}</span>
            <span>Slide {{ $index + 1 }} / {{ count($presentation->structure['slides']) }}</span>
        </div>
    </div>
@endforeach

</body>
</html>
